### ISSUE TITLE
module 'torch.amp' has no attribute 'custom_fwd'

### ISSUE THREAD

**Issue by cheezecrisp** [kijai/ComfyUI-GIMM-VFI#1]
Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2018, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GIMM-VFI\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GIMM-VFI\nodes.py", line 15, in <module>
    from .gimmvfi.generalizable_INR.gimmvfi_r import GIMMVFI_R
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GIMM-VFI\gimmvfi\generalizable_INR\gimmvfi_r.py", line 31, in <module>
    from .modules.softsplat import softsplat
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GIMM-VFI\gimmvfi\generalizable_INR\modules\softsplat.py", line 356, in <module>
    class softsplat_func(torch.autograd.Function):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GIMM-VFI\gimmvfi\generalizable_INR\modules\softsplat.py", line 358, in softsplat_func
    @torch.amp.custom_fwd(device_type="cuda", cast_inputs=torch.float32)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'torch.amp' has no attribute 'custom_fwd'

**Comment by kijai** [comment]
You probably need to update torch, I have only tested with 2.5.1

**Comment by cheezecrisp** [comment]
> You probably need to update torch, I have only tested with 2.5.1

Oh...it's a nightmare to update torch, I have to backup the python_embeded folder first. Anyway, thanks for the reply

**Comment by kijai** [comment]
> > You probably need to update torch, I have only tested with 2.5.1
> 
> Oh...it's a nightmare to update torch, I have to backup the python_embeded folder first. Anyway, thanks for the reply

Honestly haven't had any issues updating torch in a long time, 2.5.1 is worthy update anyway and highly recommended, current Comfy comes with it already too.
