### ISSUE TITLE
str expected, not NoneType

### ISSUE THREAD

**Issue by LiJT** [kijai/ComfyUI-GIMM-VFI#3]
![image](https://github.com/user-attachments/assets/d5d8009d-0955-4363-b597-66b812472fad)

Prompt executed in 53.16 seconds
got prompt
!!! Exception during processing !!! str expected, not NoneType
Traceback (most recent call last):
  File "E:\ComfyUI-aki-v1.3\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\ComfyUI-aki-v1.3\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\ComfyUI-aki-v1.3\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\ComfyUI-aki-v1.3\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-GIMM-VFI\nodes.py", line 200, in interpolate
    all_outputs = gimmvfi_model(xs, coord_inputs, t=timesteps, ds_factor=ds_factor)
  File "E:\ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-GIMM-VFI\gimmvfi\generalizable_INR\gimmvfi_f.py", line 331, in forward
    normal_inr_flows = self.predict_flow(normal_flows, coord, t, flows)
  File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-GIMM-VFI\gimmvfi\generalizable_INR\gimmvfi_f.py", line 156, in predict_flow
    tmp_pixel_latent_0 = softsplat(
  File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-GIMM-VFI\gimmvfi\generalizable_INR\modules\softsplat.py", line 316, in softsplat
    tenOut = softsplat_func.apply(tenIn, tenFlow)
  File "E:\ComfyUI-aki-v1.3\python\lib\site-packages\torch\autograd\function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "E:\ComfyUI-aki-v1.3\python\lib\site-packages\torch\amp\autocast_mode.py", line 476, in decorate_fwd
    return fwd(*args, **kwargs)
  File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-GIMM-VFI\gimmvfi\generalizable_INR\modules\softsplat.py", line 365, in forward
    cuda_launch(
  File "cupy\_util.pyx", line 64, in cupy._util.memoize.decorator.ret
  File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-GIMM-VFI\gimmvfi\generalizable_INR\modules\softsplat.py", line 266, in cuda_launch
    os.environ["CUDA_HOME"] = cupy.cuda.get_cuda_path()
  File "E:\ComfyUI-aki-v1.3\python\lib\os.py", line 685, in __setitem__
    value = self.encodevalue(value)
  File "E:\ComfyUI-aki-v1.3\python\lib\os.py", line 743, in check_str
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not NoneType

Prompt executed in 0.75 seconds

Lord Kijai, what this error might be related to? I have install the correct version of Cupy already

**Comment by LiJT** [comment]
problem fix after installing CUDA 12.4
