### ISSUE TITLE
 stack expects a non-empty TensorList

### ISSUE THREAD

**Issue by abozahran** [kijai/ComfyUI-GIMM-VFI#5]
I faced this error
![image](https://github.com/user-attachments/assets/5a39560c-bca7-4c5d-b903-0ee10f734ab9)

got prompt
0it [00:00, ?it/s]
!!! Exception during processing !!! stack expects a non-empty TensorList
Traceback (most recent call last):
  File "C:\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "C:\ComfyUI\custom_nodes\ComfyUI-GIMM-VFI\nodes.py", line 225, in interpolate
    image_tensors = torch.stack(out_images_list)
RuntimeError: stack expects a non-empty TensorList

Prompt executed in 0.08 seconds

**Comment by abozahran** [comment]
> Are there enough images on the video? As you're choosing every 32th. It's kinda saying there wasn't any images to interpolate...

what is the minimum frames in a whole video?
I tried video with 6fps ( total 12 frames ) but gave me stack expects a non-empty TensorList

and tried extended version of the same video but got ( Got an OOM, unloading all loaded models.
